package pojo;
// default package



/**
 * Picture generated by MyEclipse Persistence Tools
 */

public class Picture  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String picName;
     private Long userId;


    // Constructors

    public Picture(String picName, Long userId) {
		super();
		this.picName = picName;
		this.userId = userId;
	}


	/** default constructor */
    public Picture() {
    }

    
    /** full constructor */
  
    // Property accessors

    

    public String getPicName() {
        return this.picName;
    }
    
    public void setPicName(String picName) {
        this.picName = picName;
    }


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public Long getUserId() {
		return userId;
	}


	public void setUserId(Long userId) {
		this.userId = userId;
	}


}