package pojo;
// default package



/**
 * User generated by MyEclipse Persistence Tools
 */

public class User  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String username;
     private String password;
     private String name;
     private int age;
     private boolean gendar;
     private String phone;


    // Constructors

    public User(String username, String password, String name, int age, boolean gendar, String phone) {
		super();
		this.username = username;
		this.password = password;
		this.name = name;
		this.age = age;
		this.gendar = gendar;
		this.phone = phone;
	}


	/** default constructor */
    public User() {
    }

    
    /** full constructor */
   

   
    // Property accessors

  

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }


    public boolean isGendar() {
		return gendar;
	}


	public void setGendar(boolean gendar) {
		this.gendar = gendar;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
   

}