package com.tarena.entity;

/**
 * Person generated by MyEclipse Persistence Tools
 */

public class Person implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String sex;

	private PersonAddress home;

	private PersonAddress company;

	// Constructors

	/** default constructor */
	public Person() {
	}

	public PersonAddress getCompany() {
		return company;
	}

	public void setCompany(PersonAddress company) {
		this.company = company;
	}

	public PersonAddress getHome() {
		return home;
	}

	public void setHome(PersonAddress home) {
		this.home = home;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

}